apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-kustomization
  namespace: flux-system
resources:
  - monitoring/namespace.yaml
  - opnsense
  - docmost
  - immich
  - monitoring/loki
  - monitoring/certs
  - monitoring/kube-prometheus-stack
