apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- kyverno.yaml
- policies.yaml
- cluster-kustomization.yaml
- network-metallb-config.yaml
- network-metallb.yaml
- certmanager-helm.yaml
- certmanager-issuer.yaml
- external-secrets.yaml
- longhorn-system.yaml
- traefik.yaml
- cloudNativePg.yaml
