apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: docmost
namespace: docmost
resources:
  - namespace.yaml
  - certificate.yaml
  - helm-release.yaml
  - helm-repository.yaml
