apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: alloy-config
  namespace: monitoring
namespace: monitoring
resources:
  - alloy-helm-release.yaml
  - helm-release.yaml
  - helm-repository.yaml
configMapGenerator:
  - name: alloy
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
